theme: jekyll-theme-midnight
title: Testing Site for AK Glossary Concepts
description: Just a quick area to work on ideas for the AK F&W glossary of terms.
future: true
markdown: kramdown

collections:
  glossary:
     output: true
     permalink: /glossary/:path/
    
    
